MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "This move can be learned only\n"
	.string "once. Is that okay?$"

MoveTutor_Text_SwaggerTeach:
	.string "… … … …\n"
	.string "… … … …\p"
	.string "Ah!\n"
	.string "You broke my focus…\p"
	.string "I'm trying to gather my energy\n"
	.string "by seeing how POKéMON do it.\p"
	.string "If you'd like, I'll teach the move\n"
	.string "FOCUS ENERGY to a POKéMON of yours.$"

MoveTutor_Text_SwaggerDeclined:
	.string "What, no? Can't you get into\n"
	.string "the spirit of things?$"

MoveTutor_Text_SwaggerWhichMon:
	.string "All right, which POKéMON wants to\n"
	.string "learn how to FOCUS ENERGY?$"

MoveTutor_Text_SwaggerTaught:
	.string "I'll get back to focusing my own\n"
	.string "energy. … … … …$"

MoveTutor_Text_RolloutTeach:
	.string "Did you know that you can go from\n"
	.string "here a long way in that direction\l"
	.string "without changing direction?\p"
	.string "Good place to get a good run for\n"
	.string "whatever reason one might run.\p"
	.string "What? No, no, I'm not shady.\p"
	.string "You know what, I can teach one\n"
	.string "of your POKéMON the move SNATCH\l"
	.string "if you'd like.$"

MoveTutor_Text_RolloutDeclined:
	.string "You don't need to be shy about it.$"

MoveTutor_Text_RolloutWhichMon:
	.string "Ehehe, sure thing! It'd be great if\n"
	.string "you could keep quiet afterwards.$"

MoveTutor_Text_RolloutTaught:
	.string "I'll be here if you need my services\n"
	.string "again. Ehehe…$"

MoveTutor_Text_FuryCutterTeach:
	.string "There's a move that gets stronger\n"
	.string "when you keep using it in a row.\p"
	.string "It's a STEEL-type move, and it is\n"
	.string "wickedly cool.\p"
	.string "It's called FURY CUTTER.\n"
	.string "Want me to teach it to a POKéMON?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "We're not on the same wavelength.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "Yay!\n"
	.string "Show me which POKéMON I should teach.$"

MoveTutor_Text_FuryCutterTaught:
	.string "I get a thrill watching to see if\n"
	.string "the move keeps hitting in succession!$"

MoveTutor_MimicTeach:
	.string "Do you hear the rumblings of the\n"
	.string "volcano? It calls for the end of\l"
	.string "this town!\p"
	.string "I can teach you and your POKéMON\n"
	.string "the ways of the volcano.\p"
	.string "Do you want me to teach the move\n"
	.string "DESTRUCTION to your POKéMON?$"

MoveTutor_MimicDeclined:
	.string "Oh, well. I wanted to teach\n"
	.string "DESTRUCTION to your POKéMON.$"

MoveTutor_Text_MimicWhichMon:
	.string "Fwofwo! And so I shall!\n"
	.string "Let me see the POKéMON\l"
	.string "you wish me to teach.$"

MoveTutor_Text_MimicTaught:
	.string "DESTRUCTION is a move for all.\p"
	.string "Could you execute it to perfection\n"
	.string "one day…?$"

MoveTutor_Text_MetronomeTeach:
	.string "I want all sorts of things!\n"
	.string "But I used up my allowance…\p"
	.string "Wouldn't it be nice if there were\n"
	.string "a spell that made money appear when\l"
	.string "you waggle a finger?\p"
	.string "If you want, I can teach your POKéMON\n"
	.string "the move METRONOME.\p"
	.string "Money won't appear, but your POKéMON\n"
	.string "will waggle a finger. Yes?$"

MoveTutor_Text_MetronomeDeclined:
	.string "Okay. I'll be here if you change\n"
	.string "your mind.$"

MoveTutor_Text_MetronomeWhichMon:
	.string "Okay! I'll teach it!\n"
	.string "Which POKéMON should I teach?$"

MoveTutor_Text_MetronomeTaught:
	.string "When a POKéMON waggles its finger\n"
	.string "like a METRONOME, all sorts of nice\l"
	.string "things happen.\p"
	.string "Wouldn't it be nice if we could\n"
	.string "use it, too?$"

MoveTutor_Text_SleepTalkTeach:
	.string "Humph! My wife relies on HIDDEN\n"
	.string "POWER to predict the weather.\p"
	.string "I just DEFOG to make the sky\n"
	.string "clear myself.\p"
	.string "I can teach your POKéMON how to\n"
	.string "DEFOG, too. Interested?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "Oh, fine, fine. You want to try your\n"
	.string "luck with HIDDEN POWER, too…$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "Ah, an appreciative child!\n"
	.string "Which POKéMON should I teach?$"

MoveTutor_Text_SleepTalkTaught:
	.string "I've never once gotten my wife's\n"
	.string "coin trick right.$"

MoveTutor_Text_SubstituteTeach:
	.string "When I see the wide world from up\n"
	.string "here on the roof…\p"
	.string "I think about how nice it would be\n"
	.string "if we didn't have to sleep, so I\l"
	.string "could enjoy the wonders of night.\p"
	.string "Of course it's not possible.\n"
	.string "Giggle…\p"
	.string "I know! Would you be interested in\n"
	.string "having a POKéMON learn NIGHT SHADE?$"

MoveTutor_Text_SubstituteDeclined:
	.string "Oh, no?\p"
	.string "A POKéMON can manifest the wonder\n"
	.string "of night by itself, you know.$"

MoveTutor_Text_SubstituteWhichMon:
	.string "Giggle…\n"
	.string "Which POKéMON do you want me to\l"
	.string "teach NIGHT SHADE?$"

MoveTutor_Text_SubstituteTaught:
	.string "We human beings should enjoy our\n"
	.string "own lives to the utmost!\p"
	.string "I hope you'll get that way, too!$"

MoveTutor_Text_DynamicPunchTeach:
	.string "I can't do this anymore!\p"
	.string "It's utterly hopeless!\p"
	.string "No matter how much I train, my\n"
	.string "POKéMON don't get stronger\l"
	.string "no matter how hard I try!\p"
	.string "Argh! Punch! Punch! Punch!\n"
	.string "Punch! Punch! Punch!\p"
	.string "What, don't look at me that way!\n"
	.string "I'm only hitting the ground!\p"
	.string "Or do you want me to teach your\n"
	.string "POKéMON BODY PRESS?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "Darn! You're even making fun of me?\n"
	.string "Punch! Punch! Punch!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "What? You do? You're a good person!\n"
	.string "Which POKéMON should I teach?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "I want you to get stronger and win\n"
	.string "with a high Attack BODY PRESS!$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "Young one!\p"
	.string "Let me teach your POKéMON a secret\n"
	.string "technique shared by all dragons.\p"
	.string "Please, let me teach your POKéMON\n"
	.string "the powerful LIGHT-type move\l"
	.string "DRACO METEOR!$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "Oh…$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "Okay, which POKéMON should I teach\n"
	.string "DRACO METEOR?$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "Use it wisely! As overuse can\n"
	.string "cost you!$"

MoveTutor_Text_ExplosionTeach:
	.string "I don't intend to be going nowhere\n"
	.string "fast in the sticks like this forever.\p"
	.string "You watch me, I'll get out to the city\n"
	.string "and become a huge hit.\p"
	.string "Seriously, I'm going to cause\n"
	.string "a huge EXPLOSION of popularity!\p"
	.string "If you overheard that, I'll happily\n"
	.string "teach EXPLOSION to your POKéMON!$"

MoveTutor_Text_ExplosionDeclined:
	.string "Gaah! You're turning me down because\n"
	.string "I live in the country?$"

MoveTutor_Text_ExplosionWhichMon:
	.string "Fine! An EXPLOSION it is!\n"
	.string "Which POKéMON wants to blow up?$"

MoveTutor_Text_ExplosionTaught:
	.string "For a long time, I've taught POKéMON\n"
	.string "how to use EXPLOSION, but I've yet\l"
	.string "to ignite my own EXPLOSION…\p"
	.string "Maybe it's because deep down,\n"
	.string "I would rather stay here…$"

MoveTutor_Text_YinEnergyTeach:
	.string "A DREAMER has arrived once again.\p"
	.string "Shall I teach one of your POKéMON to\n"
	.string "harness the black power of dreams?$"

MoveTutor_Text_YangEnergyTeach:
	.string "A DREAMER has arrived once again.\p"
	.string "Shall I teach one of your POKéMON to\n"
	.string "harness the white power of dreams?$"

MoveTutor_Text_YinEnergyDeclined:
	.string "Very well, DREAMER…$"

MoveTutor_Text_YinEnergyWhichMon:
	.string "Who is the recipient?$"

MoveTutor_Text_YinEnergyTaught:
	.string "It is done…\n"
	.string "Return to me any time, DREAMER.$"
